### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by ghost** [japanesemediamanager/ShokoServer#1049]
Well, it's fresh install of it using docker. I can't import, I can't even see logs of why it's not doing anything so me providing log file will be useless unless you just want text saying "Starting Server: Complete!". 

Server Version: 
v4.1.2.0, docker

I've never had any kinds of major issues with running the Windows version of ShokoServer but the docker one seems to be just pile of trash.. Sadly I can't go back to using the Windows one without doing janky stuff like VM's.

**Comment by Cazzar** [comment]
Are you able to provide more information other than "not working"

Some information that might be useful is command used to start the server, as well as the `docker logs [shoko_container_name]` output even though you mentioend it might be useless, it can give us an idea on how things are set up and everything.

Alternatively, you can also jump on to the [discord](https://discord.gg/vpeHDsg) and we can help in a more live fashion.

**Comment by da3dsoul** [comment]
I don't know if it would actually help, but I would mount the volumes with mappings for readability inside the container.
e.g. `-v "/mnt/blah/Anime:/mnt/Anime"`

But from the looks of it, you may know more about Linux and docker than I do, which isn't a difficult achievement

**Comment by da3dsoul** [comment]
Cool glad you got it sorted

**Comment by Cazzar** [comment]
For what it's worth, while @da3dsoul managed to suggest the solution, the issue was because a `-v` parameter without a inside path it's assumed as a anonymous volume, which is in the Docker documentation here: https://docs.docker.com/storage/volumes/#choose-the--v-or---mount-flag

> In the case of named volumes, the first field is the name of the volume, and is unique on a given host machine. For anonymous volumes, the first field is omitted.

essentially what the documentation there says the parameter is in the format of `[host:]container[:mode]` where `host` is the host path, `container` is the container side path and `mode` is the mode you want the mount for, `ro/rw`

I think it'll be best for us to look at explaining this a bit better in the install documentation
