### ISSUE TITLE
TvDB for shows, Movie DB for movies

### ISSUE THREAD

**Issue by morgenman** [japanesemediamanager/ShokoServer#233]
A simple enough feature request. Disable TvDB for movies and MovieDB for shows.  It will prevent a lot of mismatched info.

**Comment by ElementalCrisis** [comment]
What shows are giving you mismatched info? Also JMM will pull from TheMovieDB if there is an entry for it, not sure if it's automatic as there's no approval system for it yet.

**Comment by da3dsoul** [comment]
Yeah, I've not encountered issues with it. If anything, I prefer to not use either if I can, because things with Live Action versions can easily be mistaken *cough* Mirai Nikki *cough*

**Comment by ElementalCrisis** [comment]
Funny enough, just ran into this issue, added the movie Perfect Blue and the TvDB link is for some Japanese Tv Series with the same name. Easily fixed by deleting the TvDB link and adding The MovieDB link but having a setting for this would help. 

Also @jmediamanager, the ability to deny community links for movies would be helpful as well.

**Comment by da3dsoul** [comment]
+1 to the exclusion option

**Comment by AreFinstad** [comment]
this could be done with trakt aswell i think. they list movies and shows each on their own. and each episode and movie there is directly linked to either tvdb or tmdb directly so there is no missmatch.

**Comment by da3dsoul** [comment]
I'm closing this. I rewrote the filter to take whether it should have a link in the given provider. The rest is not really applicable due to providers breaking the standard.
