### ISSUE TITLE
"The calling thread cannot access this object because a different thread owns it." at the end of an upgrade from 3.6.1.0

### ISSUE THREAD

**Issue by SubaruSumeragi** [japanesemediamanager/ShokoServer#509]
I have this error at the end of the upgrade processus in 3.7 beta from 3.6.1.0

[related_log.txt](https://github.com/japanesemediamanager/ShokoServer/files/584694/related_log.txt)

**Comment by da3dsoul** [comment]
Known issue. It will fix itself on next beta. Do you have all settings in settings.json in C:\ProgramData\JMMServer? If yes, then delete JMM install\JMMServer.exe.config and reinstall beta

**Comment by da3dsoul** [comment]
Actually you shouldn't need to reinstall. Just try running it

**Comment by SubaruSumeragi** [comment]
No I don't have a file named settings.json and yes JMMServer.exe.config is always here.

**Comment by da3dsoul** [comment]
Mmm that's a problem then. You should have that file, but it should be fixed in new beta. The way to fix that manually is to copy and replace your appsettings section from your config into this one and rename it to JMMServer.exe.config.
https://github.com/japanesemediamanager/ShokoServer/blob/master/JMMServer/app.config

**Comment by SubaruSumeragi** [comment]
Thanks it's working :)
